services:
  go:
    build: .
    container_name: go
    networks:
      - devops-korp
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - devops-korp
    volumes:
      - ./nginx/:/etc/nginx/conf.d/